
/*The program works with files generated by unique user visits to sub-pages
of a corporate website. The files are text files that have recorded the number
of times users have clicked through a corporate web site to reach a sub-page of
the web site. Each sub-page is identified with a number between 1 - 99 and there
are 100 entries per file, one per line. Each 
appearance of the identifying number represents a unique visit to the sub-page
So if 16 appears 7 times, it means that seven users visted sub-page 16. The 
program extracts the name of the company and the date from the filename. It then
prints the number of times each sub-page was visited and identifies the sub-
page that received the most visits.*/

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.util.Arrays;
import java.util.Scanner;

public class WebPagesStats {

	public static void main(String[] args) {

		String fileName = "CBS 20181223 PageViews.txt";
		int Visits[] = new int[101]; // 101 capacity to avoid out of bounds error
		int i = 1;
		Scanner reader;
		try { // read in the file name from root directory
			reader = new Scanner(new File("C:\\" + fileName));
			while (reader.hasNext()) {
				Visits[i] = reader.nextInt(); // populate array with sub-page numbers
				i++;

			}
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		// Read Company name from file name into String
		int j = 0;
		String companyName = "";
		while (fileName.charAt(j) != ' ') {
			companyName = companyName + fileName.charAt(j);
			j++;
		}
		System.out.println("Website name: " + companyName);

		// Extract Date from filename in YYYMMDD format
		j++;
		String date = "";
		while (fileName.charAt(j) != ' ') {
			date = date + fileName.charAt(j);
			j++;
		}

		// Print Date in YYYY-MM-DD format
		System.out.print("PageView Date: " + date.charAt(0));
		System.out.print(date.charAt(1));
		System.out.print(date.charAt(2));
		System.out.print(date.charAt(3));
		System.out.print("-");
		System.out.print(date.charAt(4));
		System.out.print(date.charAt(5));
		System.out.print("-");
		System.out.print(date.charAt(6));
		System.out.println(date.charAt(7));

		Arrays.sort(Visits); // Sort array

		// Variables used to count visits and identify most visited
		j = 1;
		int most = 1;
		int indexmost = 0;

		// count number of visits for each sub-page
		for (int index = 99; index > 0; index--) {
			if (Visits[index] == Visits[index - 1]) {
				j++;
				if (j > most) {
					most = j;
					indexmost = index;
				}

			}
			// print number of visits per sub-page
			else {
				System.out.println("WebPage " + Visits[index] + " was " + "viewed " + j + " times.");
				j = 1;
			}
			// print most visited sub-page
		}
		System.out.println("\nWebPage " + Visits[indexmost] + " was " + "viewed " + "the most at " + most + " times.");
	}
}